








/** Defines the legacy autogenerated env defaults value. */
export const LEGACY_AUTOGENERATED_ENV_DEFAULTS: Record<string, string> = {
  SKILLS_REGISTRY_URL: 'https://skills.sh',
  MCP_REGISTRY_URL: 'https://registry.modelcontextprotocol.io',
  GITHUB_TOKEN: '',
  NODE_ENV: 'development',
  LLM_MODEL: 'llama3.1',
  OLLAMA_BASE_URL: 'http://localhost:11434',
  OPENROUTER_API_KEY: '',
  OPEN_ROUTER_KEY: '',
  OPENROUTER_KEY: '',
  OPENAI_API_KEY: '',
  ANTHROPIC_API_KEY: '',
};
