import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { formatEnvValue } from './format.env.value.ts';
import { LEGACY_AUTOGENERATED_ENV_DEFAULTS } from './legacy.autogenerated.env.defaults.ts';
import { normalizeStoredEnvValue } from './normalize.stored.env.value.ts';

/** Performs the sync env file operation. */
export function syncEnvFile(
  filePath: string,
  values: Record<string, string>,
  requiredNames: Iterable<string> = Object.keys(values),
): void {
  const existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  const required = new Set(requiredNames);
  const lines = (existing ? existing.split(/\r?\n/) : []).filter((line) => {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/);
    if (!match?.[1]) {
      return true;
    }
    const key = match[1];
    const legacyDefault = LEGACY_AUTOGENERATED_ENV_DEFAULTS[key];
    if (typeof legacyDefault === 'undefined' || required.has(key)) {
      return true;
    }
    return normalizeStoredEnvValue(match[2] ?? '') !== legacyDefault;
  });
  const indexes = new Map<string, number>();

  lines.forEach((line, index) => {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (match?.[1]) {
      indexes.set(match[1], index);
    }
  });

  for (const [key, value] of Object.entries(values)) {
    const rendered = `${key}=${formatEnvValue(value)}`;
    const existingIndex = indexes.get(key);
    if (typeof existingIndex === 'number') {
      lines[existingIndex] = rendered;
    } else {
      lines.push(rendered);
    }
  }

  const normalized = lines.join('\n').replace(/\n*$/, '\n');
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, normalized, { encoding: 'utf8', mode: 0o600 });
  chmodSync(filePath, 0o600);
}
